version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-xml
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  slave:
    image: mariadb:10.3
    restart: always
    tty: true
    container_name: slave
    volumes:
    - slave:/var/lib/mysql
    - ./data/slave/etc/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: main
      MYSQL_USER: nikolai
      MYSQL_PASSWORD: 123
    ports:
    - "6060:3306"
    networks:
      - app-network

  master:
    image: mariadb:10.3
    restart: always
    tty: true
    container_name: master
    volumes:
    - master:/var/lib/mysql
    - ./data/master/etc/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: main
      MYSQL_USER: nikolai
      MYSQL_PASSWORD: 123
    ports:
    - "6061:3306"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  slave:
    driver: local
  master:
    driver: local
